// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/Loading.tsx";
import * as $$3 from "./islands/Newsletter.tsx";
import * as $$4 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/Loading.tsx": $$2,
    "./islands/Newsletter.tsx": $$3,
    "./islands/Search.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
