// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/LoadGitHubRaw.ts";
import * as $$$$$$0 from "./sections/Banner.tsx";
import * as $$$$$$1 from "./sections/Carousel.tsx";
import * as $$$$$$2 from "./sections/CircleText.tsx";
import * as $$$$$$3 from "./sections/Content/Benefits.tsx";
import * as $$$$$$4 from "./sections/Content/Faq.tsx";
import * as $$$$$$5 from "./sections/Content/Logos.tsx";
import * as $$$$$$6 from "./sections/FontText.tsx";
import * as $$$$$$7 from "./sections/Footer/Footer.tsx";
import * as $$$$$$8 from "./sections/Head.tsx";
import * as $$$$$$9 from "./sections/Header.tsx";
import * as $$$$$$10 from "./sections/Loading.tsx";
import * as $$$$$$11 from "./sections/Main/Portfolio.tsx";
import * as $$$$$$12 from "./sections/Search.tsx";
import * as $$$$$$13 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "functions": {
    "deco-sites/web/functions/LoadGitHubRaw.ts": $0,
  },
  "sections": {
    "deco-sites/web/sections/Banner.tsx": $$$$$$0,
    "deco-sites/web/sections/Carousel.tsx": $$$$$$1,
    "deco-sites/web/sections/CircleText.tsx": $$$$$$2,
    "deco-sites/web/sections/Content/Benefits.tsx": $$$$$$3,
    "deco-sites/web/sections/Content/Faq.tsx": $$$$$$4,
    "deco-sites/web/sections/Content/Logos.tsx": $$$$$$5,
    "deco-sites/web/sections/FontText.tsx": $$$$$$6,
    "deco-sites/web/sections/Footer/Footer.tsx": $$$$$$7,
    "deco-sites/web/sections/Head.tsx": $$$$$$8,
    "deco-sites/web/sections/Header.tsx": $$$$$$9,
    "deco-sites/web/sections/Loading.tsx": $$$$$$10,
    "deco-sites/web/sections/Main/Portfolio.tsx": $$$$$$11,
    "deco-sites/web/sections/Search.tsx": $$$$$$12,
    "deco-sites/web/sections/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "deco-sites/web/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/web/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/web",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
